version: '3.7'
services:
        server:
               build:
                       context: .
                       dockerfile: ./Dockerfile_server
               network_mode: host
               image: shorter_server
        goose:
                build:
                        context: .
                        dockerfile: ./Dockerfile_goose
                network_mode: host
                image: goose

