#syntax=docker/dockerfile:1

FROM golang:1.16-alpine

WORKDIR /app

COPY go.mod go.sum ./

COPY . ./

COPY ./configs/app.env /app

RUN go mod download
RUN go get github.com/pressly/goose/v3
RUN go build -o ./migrations/goose ./migrations/main.go

ENTRYPOINT ["./migrations/goose"]

